export type ContentKind = 'item' | 'block';

export interface ContentBuilderDraft {
  readonly kind: ContentKind;
  readonly id: string;
  readonly displayName: string;
  readonly textureItem: string;
  readonly maxStackSize: number;
  readonly rarity: 'common' | 'uncommon' | 'rare' | 'epic';
  readonly glow: boolean;
  readonly tooltip: string;
  readonly hardness: number;
  readonly resistance: number;
  readonly soundType: 'stone' | 'metal' | 'wood' | 'glass' | 'wool';
  readonly requiresTool: boolean;
  readonly miningTool: 'pickaxe' | 'axe' | 'shovel' | 'hoe' | 'none';
}

const RESOURCE_ID = /^[a-z0-9_.-]+:[a-z0-9_./-]+$/u;
const CONTENT_KINDS = new Set<ContentKind>(['item', 'block']);
const RARITIES = new Set<ContentBuilderDraft['rarity']>(['common', 'uncommon', 'rare', 'epic']);
const SOUND_TYPES = new Set<ContentBuilderDraft['soundType']>([
  'stone',
  'metal',
  'wood',
  'glass',
  'wool',
]);
const MINING_TOOLS = new Set<ContentBuilderDraft['miningTool']>([
  'pickaxe',
  'axe',
  'shovel',
  'hoe',
  'none',
]);

export function generateContentScript(draft: ContentBuilderDraft): string {
  validateContentDraft(draft);
  const create = draft.kind === 'item' ? generateItemBuilder(draft) : generateBlockBuilder(draft);
  return `// Generated by KubeVS. This file can be edited safely by hand.\nStartupEvents.registry(${quoted(draft.kind)}, event => {\n${create}\n})\n`;
}

export function validateContentDraft(draft: ContentBuilderDraft): void {
  if (!CONTENT_KINDS.has(draft.kind)) throw new Error('Unknown content type.');
  if (typeof draft.id !== 'string') throw new Error('The ID must be a string.');
  if (!RESOURCE_ID.test(draft.id)) throw new Error('The ID must use the namespace:name format.');
  if (typeof draft.displayName !== 'string') throw new Error('The display name must be a string.');
  if (!draft.displayName.trim()) throw new Error('Enter an in-game display name.');
  if (draft.displayName.length > 120)
    throw new Error('The display name cannot exceed 120 characters.');
  if (typeof draft.textureItem !== 'string') throw new Error('The icon ID must be a string.');
  if (draft.textureItem && !RESOURCE_ID.test(draft.textureItem)) {
    throw new Error('The icon sample must be an in-game ID.');
  }
  if (!RARITIES.has(draft.rarity)) throw new Error('Unknown rarity selected.');
  if (typeof draft.glow !== 'boolean') throw new Error('The glow setting must be boolean.');
  if (typeof draft.tooltip !== 'string' || draft.tooltip.length > 2_000) {
    throw new Error('The tooltip must be a string no longer than 2000 characters.');
  }
  if (!SOUND_TYPES.has(draft.soundType)) throw new Error('Unknown sound type selected.');
  if (typeof draft.requiresTool !== 'boolean') {
    throw new Error('The tool requirement must be boolean.');
  }
  if (!MINING_TOOLS.has(draft.miningTool)) throw new Error('Unknown mining tool selected.');
  if (draft.kind === 'block' && draft.requiresTool && draft.miningTool === 'none') {
    throw new Error('Select a mining tool when requiring the correct tool.');
  }
  if (
    !Number.isSafeInteger(draft.maxStackSize) ||
    draft.maxStackSize < 1 ||
    draft.maxStackSize > 64
  ) {
    throw new Error('Stack size must be an integer from 1 to 64.');
  }
  for (const [label, value] of [
    ['Hardness', draft.hardness],
    ['Blast resistance', draft.resistance],
  ] as const) {
    if (!Number.isFinite(value) || value < 0 || value > 3_600_000) {
      throw new Error(`${label}: expected a number from 0 to 3600000.`);
    }
  }
}

export function suggestedContentId(displayName: string, fallback = 'new_content'): string {
  const transliterated = displayName
    .trim()
    .toLocaleLowerCase('en-US')
    .replace(/[^a-z0-9_.-]+/gu, '_')
    .replace(/^_+|_+$/gu, '')
    .slice(0, 80);
  return `kubejs:${transliterated || fallback}`;
}

function generateItemBuilder(draft: ContentBuilderDraft): string {
  const lines = [
    `  event.create(${quoted(draft.id)})`,
    `    .displayName(${quoted(draft.displayName.trim())})`,
    `    .maxStackSize(${draft.maxStackSize})`,
    `    .rarity(${quoted(draft.rarity)})`,
  ];
  if (draft.glow) lines.push('    .glow(true)');
  if (draft.tooltip.trim()) lines.push(`    .tooltip(${quoted(draft.tooltip.trim())})`);
  return lines.join('\n');
}

function generateBlockBuilder(draft: ContentBuilderDraft): string {
  const lines = [
    `  event.create(${quoted(draft.id)})`,
    `    .displayName(${quoted(draft.displayName.trim())})`,
    `    .soundType(${quoted(draft.soundType)})`,
    `    .hardness(${draft.hardness})`,
    `    .resistance(${draft.resistance})`,
  ];
  if (draft.requiresTool) lines.push('    .requiresTool(true)');
  if (draft.miningTool !== 'none') {
    lines.push(`    .tagBlock(${quoted(`minecraft:mineable/${draft.miningTool}`)})`);
  }
  return lines.join('\n');
}

function quoted(value: string): string {
  return JSON.stringify(value);
}
